version: "3.8"
services:
  web:
    build: .
    image: teds12:1.0
    depends_on:
      - db
    ports:
      - 8069:8069
    environment:
    - HOST=10.23.7.114
    - USER=odoo
    - PASSWORD=P@ssw0rd
    - DB=teds
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: