{
    "name":"Work Order",
    "version":"1.0",
    "author":"PT.WITACO",
    "category":"TDM",
    "description": """
        Addons Work Order
    """,
    "depends":["base","wtc_faktur_pajak","wtc_branch","hr","account","wtc_account","wtc_sequence","wtc_dealer_menu","wtc_serial_number"],
    "init_xml":[],
    "demo_xml":[],
    "data":[
                
                  'wizard/wtc_work_order_wip_view.xml',
                  'views/wtc_work_order_wip_report.xml', 
                  "wtc_work_order_report.xml",
                  "wtc_work_order_view.xml",
                  "wtc_kpb_expired_view.xml",                  
                  "wtc_start_stop_wo_view.xml",
                  "wtc_production_stock_lot_view.xml",
                  "wtc_collecting_kpb_view.xml",
                  "wtc_approval_wo_view.xml",
                  'wtc_kpb_engine_type_view.xml',
                  'wtc_harga_jasa_view.xml',
                  "wtc_collecting_kpb_workflow.xml",
                  "wtc_work_order_workflow.xml",
                  "wtc_branch_config_data.xml",
                  'security/ir.model.access.csv',
                  'security/res_groups.xml',
                  'security/ir_rule.xml',
                  'report/work_order_report_view.xml',
                  
                  #'data/wtc.kpb.engine.type.csv',
                  #'data/wtc.kpb.engine.price.csv',
                  #'data/wtc.kpb.expired.xml',
                  #'data/wtc.workshop.category.csv',
                  #'data/product.product.csv',
                  #'data/product.category.csv',
                  #'data/wtc.harga.jasa.csv',
                  #'data/ir.sequence.xml',
#                   'data/product.product.xml',
#                   'data/wtc.branch.config.xml',
#                 'data/wtc.workshop.category.xml',
                 'data/wtc.kpb.engine.type.xml',
                 'data/wtc.kpb.engine.price.xml',
#                 'data/wtc.kpb.expired.xml',
#                 'data/wtc.harga.jasa.xml',
#                 'data/wtc_approval_config_data.xml',
                  'views/wtc_report_work_order_wo_report.xml',
                  'views/wtc_report_work_order_picking.xml',
                  'views/wtc_work_order_invoice_report.xml',
                  'wizard/teds_work_order_import_wizard.xml',
                  
                  ],
    "installable":True,
    "active":False,
}

