{
    "name":"Petty Cash",
    "version":"1.0",
    "author":"PT. WITACO",
    "website":"http://witaco.com",
    "category":"TDM",
    "description": """
        PettyCash Out
    """,
    "depends":["base",
               "account",
               "wtc_dealer_menu",
               "wtc_approval",
               "wtc_branch",
               "wtc_account_filter",
               "wtc_account_move",
               "teds_payment_request_type",
               ],
    "init_xml":[],
    "demo_xml":[],
    "data":[  
            'security/ir.model.access.csv',
            'security/ir_rule.xml', 
            "security/res_groups.xml",        
            "security/res_groups_button.xml",     
            "wtc_petty_cash_out_report.xml",
            "wtc_pettycash_out_workflow.xml",    
            "wtc_pettycash_out_view.xml",  
            "wtc_pettycash_in_view.xml",
            'wtc_reimbursed_view.xml',                                         
            "wtc_approval_pettycash_out_workflow.xml",              
            "wtc_approval_pettycash_out_view.xml",           
#             'data/ir.sequence.xml',
#             'data/account.journal.xml',
            'data/wtc_approval_config_data.xml',
              ],
    "active":False,
    "installable":True
}