{
    "name":"Product",
    "version":"1.0",
    "author":"PT. WITACO",
    "website":"http://witaco.com",
    "category":"TDM",
    "description":"Master Product",
    "depends":["base","product","account"],
    "init_xml":[],
    "demo_xml":[],
    "data":[
            "wtc_product_view.xml",
            "security/ir.model.access.csv",
#             "data/product.category.xml",
#             "data/product.template.xml",                        
#             "data/product.product.xml",
#             "data/product.attribute.value.xml",
#             "data/product.attribute.xml",            
#             "data/product.attribute.line.xml",
#             "data/wtc.barang.extras.xml",
#             "data/product.category.csv",
#             "data/product.attribute.csv",
#             "data/product.attribute.value.csv",
            "security/res_groups.xml",
            ],
    "active":False,
    "installable":True
}