{
    "name":"Permohonan Faktur",
    "version":"1.0",
    "author":"PT. WITACO",
    "website":"http://witaco.com",
    "category":"TDM",
    "description": """
        Permohonan Faktur
    """,
    "depends":["base",
               "wtc_res_partner_cddb",
               "account_voucher",
               "account",
               "wtc_branch",
               "stock",
               "wtc_dealer_menu",
               "wtc_serial_number",
               "wtc_approval"
               ],
    "init_xml":[],
    "demo_xml":[],
    "data":[
            'security/ir.model.access.csv',
            'security/ir_rule.xml',          
            "wtc_permohonan_faktur_workflow.xml",
            "wtc_approval_permohonan_faktur_workflow.xml",  
            "wtc_outstanding_permohonan_faktur_view.xml",
            "wtc_permohonan_faktur_view.xml",
            "wtc_approval_permohonan_faktur_view.xml",
            "wtc_penerimaan_faktur_view.xml",
            "wtc_serial_number_pf_view.xml",
            "wtc_penyerahan_faktur_view.xml",
            'wtc_cancel_penerimaan_faktur_view.xml',                          
            'data/wtc_approval_config_data.xml',
            'security/res_groups.xml',   
            'security/res_groups_button.xml',  
            'wtc_serial_number_data.xml',  
              ],
    "active":False,
    "installable":True
}