{
    "name": "TEDS NRFS",
    "version": "1.0",
    "depends": [
        'base',
        'web_readonly_bypass',
        'account',
        'wtc_dealer_menu',
        'wtc_address',
        'wtc_res_partner',
        'b2b_file',
        'wtc_branch',
        'wtc_stock',
        'wtc_work_order',
        'teds_report_google_drive'
    ],
    "author": "FAL",
    "category": "Custom Modules",
    "summary": "Penanganan Unit NRFS",
    "description": """
        Digitalisasi proses perbaikan unit NRFS hingga menjadi stok RFS
    """,
    "demo": [],
    "data": [
        "views/teds_partner_view.xml",
        "views/teds_nrfs_master_gejala_view.xml",
        "views/teds_nrfs_master_penyebab_view.xml",
        "views/teds_nrfs_master_penanganan_unit_view.xml",
        "data/teds_nrfs_master_gejala_data.xml",
        "data/teds_nrfs_master_penyebab_data.xml",
        "data/teds_nrfs_master_penanganan_unit_data.xml",
        "data/teds_nrfs_partner_lkuas_data.xml",
        "data/teds_nrfs_cron.xml",
        "data/teds_po_urgent_sequence.xml",
        "views/teds_menu.xml",
        "views/teds_nrfs_view.xml",
        "views/teds_nrfs_vendor_view.xml",
        "views/teds_po_urgent_view.xml",
        "views/teds_work_order_view.xml",
        "views/teds_stock_packing_md_view.xml",
        "views/teds_mft_file_view.xml",
        "reports/teds_po_urgent_report_view.xml",
        "reports/teds_nrfs_report_view.xml",
        "reports/teds_nrfs_report_google_drive_view.xml",
        "security/ir.model.access.csv",
        "security/res_groups.xml",
        "security/res_groups_button.xml",
        "security/ir_rule.xml",
    ],
}