{
    "name":"Master Branch",
    "version":"1.0",
    "author":"PT. WITACO",
    "website":"www.witaco.com",
    "category":"TDM",
    "description": """
        Master Branch
    """,
    "depends":["base","wtc_address","product","hr","stock","account","wtc_dealer_menu"],
    "init_xml":[],
    "demo_xml":[],
    "data":[
                  "wtc_branch_view.xml",
                  "wtc_harga_birojasa_view.xml",
                  "wtc_harga_bbn_view.xml",
                  "wtc_branch_data.xml",
                  "wtc_branch_category_view.xml",
                  "wtc_area_view.xml",
                  "res_users_view.xml",
                  'security/ir.model.access.csv',
                  "wtc_branch_config_view.xml",
                  "wtc_harga_ekspedisi_view.xml",
                'data/res_groups.xml',
#                 'data/res_groups_audit.xml',
#                   "data/wtc.branch.xml",
#                   "data/account.journal.xml",
#                   "data/wtc.branch.config.xml",
#                   "data/wtc.area.xml",
#                   'data/wtc.branch.csv',
#                   'data/wtc.area.csv',
#                   'data/wtc.branch.config.csv',
                  #'data/account.account',
                  "security/res_groups.xml",
                  ],
    "active":False,
    "installable":True
}