{
    "name":"Payments",
    "version":"1.0",
    "author":"PT. WITACO",
    "website":"http://witaco.com",
    "category":"TDM",
    "description":"Payments",
    "depends":["base","wtc_register_kwitansi","wtc_faktur_pajak","wtc_branch","wtc_jumlah_cetak","account_voucher","wtc_account_journal","wtc_account_filter","wtc_account_move","wtc_hpp"],
    "init_xml":[],
    "demo_xml":[],
    "data":[
                  "wtc_account_voucher_report.xml",
                  "wtc_approval_account_voucher_workflow.xml",
                  "wtc_account_voucher_view.xml",
                  "wtc_approval_account_voucher_view.xml",                  
                  "wtc_branch_config_view.xml",
                  'security/ir.model.access.csv',
                  "report/wtc_account_move_line_receivable.xml",
#                   'data/wtc.branch.config.xml',
                  #'data/wtc_account_filter_data.xml',
#                   'data/ir.sequence.xml',
                  'data/wtc_approval_config_data.xml',
                  'wtc_customer_payment_view.xml',
                  'wtc_supplier_payment_view.xml',
                  'wtc_register_kwitansi_view.xml',
                  'wtc_hutang_lain_view.xml',
                  "security/res_groups.xml",
                  "security/res_groups_button.xml",
                  'security/ir_rule.xml',
                  'security/new_res_groups.xml',
                  'view/wtc_supplier_payment_report_new.xml',

                  ],
    "active":False,
    "installable":True
}
