{
    "name":"Dealer Sale Order",
    "version":"1.0",
    "author":"ABK",
    "email":"anggar.bagus@gmail.com",
    "website":"http://teds.tunasdwipamatra.com",
    "category":"TDM",
    "description": """
        Dealer Sale Order
    """,
    "depends":["base","product","wtc_branch","wtc_faktur_pajak","account","wtc_program_subsidi","wtc_res_partner_cddb","wtc_serial_number","account","account_voucher"],
    "init_xml":[],
    "demo_xml":[],
    "data":[       
                   'security/ir.model.access.csv',
                   'security/ir_rule.xml',
                   'security/res_groups.xml',
                   'security/res_groups_button.xml',
                   'views/report_test.xml',
                   #'report/dealer_sale_order_analysis_view.xml',            
                   #'wizard/dealer_sale_order_report_wizard.xml',
                   'views/dealer_spk_report_vew.xml',
                   "customer_invoice_view.xml",                   
                   #'views/dealer_sale_order_report.xml',
                   "dealer_sale_order_report.xml",
                   "dealer_sale_order_view.xml",
                   "dealer_sale_order_workflow.xml",
                   "dealer_spk_view.xml",
                   "wtc_serial_number_view.xml",
                   "wtc_branch_config_view.xml",
                   "dealer_register_spk_view.xml",
                   "dealer_generate_register_spk_view.xml",
                   "dealer_distribusi_spk_view.xml",
                   "dealer_pengembalian_spk_view.xml",
                   "dealer_approval_sale_order_view.xml",
#                    "wtc_outgoing_shipments_showroom.xml",
#                    "wtc_outgoing_shipments_workshop.xml",
                    "wtc_on_outgoing_shipments.xml",
                    "views/wtc_report_print_subsidi_leasing.xml",
                   #'data/wtc.branch.config.xml',
                   #'data/ir.sequence.xml',
#                    'data/wtc_approval_config_data.xml',
                   "views/teds_dealer_sale_order_surat_kuasa_view.xml",
                   "report/teds_dealer_sale_order_surat_kuasa_print.xml",
                   ],
    'qweb' : [
        "static/src/xml/dealer_spk_report.xml"
    ],
    "active":False,
    "installable":True
}