{
    "name":"Bank Transfer",
    "version":"1.0",
    "author":"PT. WITACO",
    "website":"http://witaco.com",
    "category":"TDM",
    "description": """
        Bank Transfer
    """,
    "depends":["base","wtc_branch","account","wtc_account_move","wtc_pettycash","wtc_bank_reconcile"],
    "init_xml":[],
    "demo_xml":[],
    "data":[  
            'wtc_bank_transfer_report_view.xml',
            'wtc_cancel_bank_transfer_view.xml',
            'data/wtc_approval_config_data.xml',
            'data/wtc_branch_config.xml',
            'security/res_groups.xml',            
            "security/res_groups_button.xml",
            "wtc_bank_transfer_workflow.xml",   
            "wtc_approval_bank_transfer_workflow.xml", 
            "wtc_bank_transfer_view.xml",   
            "wtc_approval_bank_transfer_view.xml",
            "wtc_branch_config_view.xml",
            'security/ir.model.access.csv',
            'security/ir_rule.xml',
            'wtc_bank_statement_view.xml',
            'wtc_account_journal_view.xml',
            'report/wtc_bank_transfer_report.xml',
            'report/teds_bank_transfer_cancel.xml',
            'report/teds_bank_transfer_cancel_print.xml',
            #'data/account.account.xml',
#             'data/ir.sequence.xml',
#             'data/account.journal.xml',
#             'data/res.bank.xml',
#             'data/res.partner.bank.xml',
              ],
    "active":False,
    "installable":True
}